name: Test Homebrew formula

on:
  push:
    branches: [main]
    paths:
      - 'Formula/**'
      - '.github/workflows/test.yml'
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Install from tap
        run: brew install arika0093/console2svg/console2svg

      - name: Run formula test
        run: brew test arika0093/console2svg/console2svg
